"""Integer partition generation utilities.

This module provides functions for generating integer partitions of a
positive integer n. Partitions are generated by recursively merging
adjacent parts under a dominance-style constraint.
"""

import logging

logger = logging.getLogger(__name__)


def generate_partitions(curr, i, partitions):
    """Generate partitions by recursively merging adjacent parts.

    This function explores all possible ways to merge adjacent parts in
    a partition such that no element in the left rest exceeds the sum
    of the merged pair.

    Parameters
    ----------
    curr : list
        Current partition state.
    i : int
        Current index in the partition.
    partitions : list
        List to collect all generated partitions.

    Notes
    -----
    This recursive algorithm generates partitions by exploring all possible
    merges of adjacent parts. A merge (curr[i] + curr[i+1]) is valid only if
    the result does not exceed any element in the prefix [curr[0], ..., curr[i-1]].

    The algorithm implements a depth-first traversal of the merge tree,
    following a dominance-style constraint typical in integer partition
    combinatorics.

    """
    if i >= len(curr) - 1:
        logger.debug("Base case: index %d >= len(%s) - 1 = %d, returning", i, curr, len(curr) - 1)
        return

    pair_sum = curr[i] + curr[i + 1]
    constraint_passes = all(pair_sum <= k for k in curr[:i])

    logger.debug("Checking merge at index %d: curr=%s, pair_sum=%d, constraint_passes=%s",
                 i, curr, pair_sum, constraint_passes)

    if constraint_passes:
        new_partition = curr[:i] + [pair_sum] + curr[i + 2:]
        partitions.append(new_partition)
        logger.debug("Merged at index %d: %s -> %s, total partitions: %d",
                     i, curr, new_partition, len(partitions))

        # left child
        logger.debug("Exploring left child from %s at index %d", new_partition, i)
        generate_partitions(new_partition, i, partitions)
        # right child
        logger.debug("Exploring right child from %s at index %d", curr, i + 1)
        generate_partitions(curr, i + 1, partitions)
    else:
        # no valid pair found, move to next index
        logger.debug("Constraint failed at index %d, moving to next index", i)
        generate_partitions(curr, i + 1, partitions)


def integer_partitions(n):
    """Generate all integer partitions of n padded with zeros.

    This function generates all partitions of a positive integer n and
    pads shorter partitions with zeros to ensure uniform length.

    Parameters
    ----------
    n : int
        Positive integer to partition.

    Returns
    -------
    list
        List of all partitions, each padded to length n with zeros.

    Notes
    -----
    Partitions are generated by merging adjacent parts starting from the
    base partition [1, 1, ..., 1] (n ones). Only sums of entries i and i+1
    are made and replaced if no element in the left rest exceeds the sum.

    Partitions are padded with zeros to uniform length n. This simplifies
    subsequent processing in formal context construction.
    """
    logger.info("Generating integer partitions for n=%d", n)

    partitions = []
    first = [1] * n
    partitions.append(first)
    logger.debug("Added base partition: %s", first)

    if n == 1:
        logger.debug("n=1 is base case, returning %d partition(s)", len(partitions))
        return partitions

    logger.debug("Starting recursive partition generation from base partition")
    generate_partitions(first, 0, partitions)
    logger.debug("Generated %d partition(s) before padding", len(partitions))

    # fill in all remaining n-k entries for lists of length k with 0s
    for p in partitions:
        pad_length = n - len(p)
        if pad_length > 0:
            p.extend([0] * pad_length)
            logger.debug("Padded partition %s with %d zero(s)", tuple(p), pad_length)

    logger.info("Completed integer partition generation for n=%d: %d partition(s)", n, len(partitions))
    return partitions
